image: Ubuntu2204  # образ для сборки

stack: node 20  # окружение

branches:
  only:
    - master  # ветка git
    - main

cache: node_modules  # кеширование

install:
  - yarn  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - yarn build   # команда сборки

test_script:
  - yarn lint && yarn test  # скрипт тестирования

deploy_script:  # скрипт развёртывания
  - git config --global user.name "AppVeyor"
  - git config --global user.email "ci@appveyor.com"
  - git checkout --orphan gh-pages  # Создаём (или переключаемся на) gh-pages
  - git --work-tree dist add --all
  - git commit -m "Deploy to GitHub Pages"
  - git push -f origin gh-pages
